name: Integration tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i

      - name: Start OpenHIM stack
        run: |
          cd tests
          docker-compose up -d
          sleep 20
          node openhimConfig.js

      - name: Run integration tests
        run: npm run test:integration

      - name: Run linting
        run: npm run test:lint
